const KEYWORD_LABELS = {
  label: {
    ar: 'الكلمات المفتاحية المستهدفة (Focus Keywords)',
    en: 'Focus Keywords (Target Keywords)',
    zh: '目标关键词（焦点关键词）',
    es: 'Palabras clave objetivo (Focus Keywords)',
    hi: 'फ़ोकस कीवर्ड (लक्ष्य कीवर्ड)',
    fr: 'Mots-clés ciblés (Focus Keywords)',
    bn: 'ফোকাস কীওয়ার্ড (টার্গেট কীওয়ার্ড)',
    pt: 'Palavras-chave de foco (Focus Keywords)',
    ru: 'Целевые ключевые слова (Focus Keywords)',
    ja: 'フォーカスキーワード（ターゲットキーワード）',
    de: 'Fokus-Keywords (Ziel-Keywords)',
    ko: '포커스 키워드(타겟 키워드)',
    tr: 'Hedef Anahtar Kelimeler (Focus Keywords)',
    vi: 'Từ khóa trọng tâm (Focus Keywords)',
    it: 'Parole chiave focus (Focus Keywords)',
    th: 'คีย์เวิร์ดหลัก (Focus Keywords)',
    fa: 'کلمات کلیدی هدف (Focus Keywords)',
    sw: 'Maneno muhimu yaliyolengwa (Focus Keywords)',
    id: 'Kata Kunci Fokus (Focus Keywords)',
    nl: 'Focus keywords (doelzoekwoorden)',
  },
  placeholder: {
    ar: 'اكتب الكلمة واضغط Enter أو فاصلة...',
    en: 'Type keyword and press Enter or comma...',
    zh: '输入关键词并按回车或逗号...',
    es: 'Escribe la palabra y presiona Enter o coma...',
    hi: 'कीवर्ड टाइप करें और Enter या कॉमा दबाएं...',
    fr: 'Tapez le mot-clé et appuyez sur Entrée ou virgule...',
    bn: 'কীওয়ার্ড টাইপ করুন এবং Enter বা কমা চাপুন...',
    pt: 'Digite a palavra-chave e pressione Enter ou vírgula...',
    ru: 'Введите ключевое слово и нажмите Enter или запятую...',
    ja: 'キーワードを入力してEnterまたはカンマを押してください...',
    de: 'Geben Sie das Keyword ein und drücken Sie Enter oder Komma...',
    ko: '키워드를 입력하고 Enter 또는 쉼표를 누르세요...',
    tr: 'Anahtar kelimeyi yazın ve Enter veya virgüle ayırın...',
    vi: 'Nhập từ khóa và nhấn Enter hoặc dấu phẩy...',
    it: 'Digita la parola chiave e premi Invio o virgola...',
    th: 'พิมพ์คำค้นแล้วกด Enter หรือจุลภาค...',
    fa: 'کلمه کلیدی را تایپ کرده و Enter یا کاما را فشار دهید...',
    sw: 'Andika neno muhimu na bonyeza Enter au koma...',
    id: 'Ketik kata kunci dan tekan Enter atau koma...',
    nl: 'Typ het trefwoord en druk op Enter of komma...',
  },
  hint: {
    ar: 'اضغط Enter أو اكتب فاصلة لإضافة كلمة. يمكنك لصق قائمة كلمات مفصولة بفواصل.',
    en: 'Press Enter or type a comma to add. You can paste a comma-separated list.',
    zh: '按Enter或输入逗号添加。您可以粘贴逗号分隔的列表。',
    es: 'Presiona Enter o escribe una coma para agregar. Puedes pegar una lista separada por comas.',
    hi: 'जोड़ने के लिए Enter दबाएं या कॉमा टाइप करें। आप कॉमा से अलग की गई सूची चिपका सकते हैं।',
    fr: 'Appuyez sur Entrée ou tapez une virgule pour ajouter. Vous pouvez coller une liste séparée par des virgules.',
    bn: 'যোগ করতে Enter চাপুন বা কমা টাইপ করুন। আপনি কমা দ্বারা পৃথক তালিকা পেস্ট করতে পারেন।',
    pt: 'Pressione Enter ou digite uma vírgula para adicionar. Você pode colar uma lista separada por vírgulas.',
    ru: 'Нажмите Enter или введите запятую, чтобы добавить. Вы можете вставить список, разделенный запятыми.',
    ja: '追加するにはEnterを押すかカンマを入力します。カンマ区切りのリストを貼り付けることもできます。',
    de: 'Drücken Sie Enter oder geben Sie ein Komma ein, um hinzuzufügen. Sie können eine kommagetrennte Liste einfügen.',
    ko: '추가하려면 Enter를 누르거나 쉼표를 입력하세요. 쉼표로 구분된 목록을 붙여넣을 수 있습니다.',
    tr: 'Eklemek için Enter tuşuna basın veya virgül yazın. Virgülle ayrılmış bir listeyi yapıştırabilirsiniz.',
    vi: 'Nhấn Enter hoặc gõ dấu phẩy để thêm. Bạn có thể dán danh sách cách nhau bằng dấu phẩy.',
    it: 'Premi Invio o digita una virgola per aggiungere. Puoi incollare un elenco separato da virgole.',
    th: 'กด Enter หรือพิมพ์จุลภาคเพื่อเพิ่ม คุณสามารถวางรายการที่คั่นด้วยจุลภาคได้',
    fa: 'برای افزودن Enter یا کاما را فشار دهید. می‌توانید لیستی جدا شده با کاما را جایگذاری کنید.',
    sw: 'Bonyeza Enter au chapa koma kuongeza. Unaweza kubandika orodha iliyotengwa na koma.',
    id: 'Tekan Enter atau ketik koma untuk menambahkan. Anda dapat menempelkan daftar yang dipisahkan koma.',
    nl: 'Druk op Enter of typ een komma om toe te voegen. U kunt een door komma\'s gescheiden lijst plakken.',
  },
  analysisHeader: {
    ar: 'تحليل السيو الفوري (Live SEO Analysis)',
    en: 'Live SEO Analysis',
    zh: '实时SEO分析',
    es: 'Análisis SEO en vivo',
    hi: 'लाइव SEO विश्लेषण',
    fr: 'Analyse SEO en direct',
    bn: 'লাইভ এসইও বিশ্লেষণ',
    pt: 'Análise de SEO ao vivo',
    ru: 'Живой SEO-анализ',
    ja: 'ライブSEO分析',
    de: 'Live-SEO-Analyse',
    ko: '실시간 SEO 분석',
    tr: 'Canlı SEO Analizi',
    vi: 'Phân tích SEO trực tiếp',
    it: 'Analisi SEO in tempo reale',
    th: 'การวิเคราะห์ SEO แบบเรียลไทม์',
    fa: 'تحلیل سئوی زنده',
    sw: 'Uchambuzi wa SEO wa moja kwa moja',
    id: 'Analisis SEO Langsung',
    nl: 'Live SEO-analyse',
  },
  inTitle: {
    ar: 'في العنوان',
    en: 'In title',
    zh: '在标题中',
    es: 'En el título',
    hi: 'शीर्षक में',
    fr: 'Dans le titre',
    bn: 'শিরোনামে',
    pt: 'No título',
    ru: 'В заголовке',
    ja: 'タイトル内',
    de: 'Im Titel',
    ko: '제목에 포함',
    tr: 'Başlıkta',
    vi: 'Trong tiêu đề',
    it: 'Nel titolo',
    th: 'ในชื่อเรื่อง',
    fa: 'در عنوان',
    sw: 'Kwenye kichwa',
    id: 'Di judul',
    nl: 'In titel',
  },
  missingTitle: {
    ar: 'مفقود من العنوان',
    en: 'Missing from title',
    zh: '标题中缺失',
    es: 'Falta en el título',
    hi: 'शीर्षक से गायब',
    fr: 'Manquant dans le titre',
    bn: 'শিরোনামে অনুপস্থিত',
    pt: 'Ausente do título',
    ru: 'Отсутствует в заголовке',
    ja: 'タイトルにありません',
    de: 'Fehlt im Titel',
    ko: '제목에 없음',
    tr: 'Başlıkta eksik',
    vi: 'Thiếu trong tiêu đề',
    it: 'Mancante nel titolo',
    th: 'ขาดจากชื่อเรื่อง',
    fa: 'در عنوان وجود ندارد',
    sw: 'Haipo kwenye kichwa',
    id: 'Tidak ada di judul',
    nl: 'Ontbreekt in titel',
  },
  inDescription: {
    ar: 'في الوصف',
    en: 'In description',
    zh: '在描述中',
    es: 'En la descripción',
    hi: 'विवरण में',
    fr: 'Dans la description',
    bn: 'বর্ণনায়',
    pt: 'Na descrição',
    ru: 'В описании',
    ja: '説明内',
    de: 'In der Beschreibung',
    ko: '설명에 포함',
    tr: 'Açıklamada',
    vi: 'Trong mô tả',
    it: 'Nella descrizione',
    th: 'ในคำอธิบาย',
    fa: 'در توضیحات',
    sw: 'Kwenye maelezo',
    id: 'Di deskripsi',
    nl: 'In beschrijving',
  },
  missingDescription: {
    ar: 'مفقود من الوصف',
    en: 'Missing from description',
    zh: '描述中缺失',
    es: 'Falta en la descripción',
    hi: 'विवरण से गायब',
    fr: 'Manquant dans la description',
    bn: 'বর্ণনায় অনুপস্থিত',
    pt: 'Ausente da descrição',
    ru: 'Отсутствует в описании',
    ja: '説明にありません',
    de: 'Fehlt in der Beschreibung',
    ko: '설명에 없음',
    tr: 'Açıklamada eksik',
    vi: 'Thiếu trong mô tả',
    it: 'Mancante nella descrizione',
    th: 'ขาดจากคำอธิบาย',
    fa: 'در توضیحات وجود ندارد',
    sw: 'Haipo kwenye maelezo',
    id: 'Tidak ada di deskripsi',
    nl: 'Ontbreekt in beschrijving',
  },
  goodFrequency: {
    ar: 'تكرار مناسب',
    en: 'Good frequency',
    zh: '频率适中',
    es: 'Buena frecuencia',
    hi: 'अच्छी आवृत्ति',
    fr: 'Bonne fréquence',
    bn: 'ভালো ফ্রিকোয়েন্সি',
    pt: 'Boa frequência',
    ru: 'Хорошая частота',
    ja: '適切な頻度',
    de: 'Gute Häufigkeit',
    ko: '적절한 빈도',
    tr: 'İyi sıklık',
    vi: 'Tần suất tốt',
    it: 'Buona frequenza',
    th: 'ความถี่เหมาะสม',
    fa: 'تکرار مناسب',
    sw: 'Mara nzuri',
    id: 'Frekuensi baik',
    nl: 'Goede frequentie',
  },
  overused: {
    ar: 'تكرار مفرط',
    en: 'Overused',
    zh: '过度使用',
    es: 'Uso excesivo',
    hi: 'अत्यधिक उपयोग',
    fr: 'Surutilisé',
    bn: 'অতিরিক্ত ব্যবহার',
    pt: 'Uso excessivo',
    ru: 'Чрезмерное использование',
    ja: '使いすぎ',
    de: 'Übermäßig genutzt',
    ko: '과도하게 사용됨',
    tr: 'Aşırı kullanım',
    vi: 'Sử dụng quá nhiều',
    it: 'Uso eccessivo',
    th: 'ใช้มากเกินไป',
    fa: 'استفاده بیش از حد',
    sw: 'Imetumika kupita kiasi',
    id: 'Terlalu sering',
    nl: 'Overmatig gebruikt',
  },
  goodDensity: {
    ar: 'كثافة مناسبة',
    en: 'Good density',
    zh: '密度适中',
    es: 'Buena densidad',
    hi: 'अच्छा घनत्व',
    fr: 'Bonne densité',
    bn: 'ভালো ঘনত্ব',
    pt: 'Boa densidade',
    ru: 'Хорошая плотность',
    ja: '適切な密度',
    de: 'Gute Dichte',
    ko: '적절한 밀도',
    tr: 'İyi yoğunluk',
    vi: 'Mật độ tốt',
    it: 'Buona densità',
    th: 'ความหนาแน่นเหมาะสม',
    fa: 'تراکم مناسب',
    sw: 'Uzani mzuri',
    id: 'Kepadatan baik',
    nl: 'Goede dichtheid',
  },
  highDensity: {
    ar: 'كثافة عالية',
    en: 'High density',
    zh: '密度过高',
    es: 'Alta densidad',
    hi: 'उच्च घनत्व',
    fr: 'Haute densité',
    bn: 'উচ্চ ঘনত্ব',
    pt: 'Alta densidade',
    ru: 'Высокая плотность',
    ja: '高密度',
    de: 'Hohe Dichte',
    ko: '높은 밀도',
    tr: 'Yüksek yoğunluk',
    vi: 'Mật độ cao',
    it: 'Alta densità',
    th: 'ความหนาแน่นสูง',
    fa: 'تراکم بالا',
    sw: 'Uzani wa juu',
    id: 'Kepadatan tinggi',
    nl: 'Hoge dichtheid',
  },
  inTitleCount: {
    ar: 'في العنوان: ',
    en: 'In title: ',
    zh: '在标题中: ',
    es: 'En el título: ',
    hi: 'शीर्षक में: ',
    fr: 'Dans le titre: ',
    bn: 'শিরোনামে: ',
    pt: 'No título: ',
    ru: 'В заголовке: ',
    ja: 'タイトル内: ',
    de: 'Im Titel: ',
    ko: '제목: ',
    tr: 'Başlıkta: ',
    vi: 'Trong tiêu đề: ',
    it: 'Nel titolo: ',
    th: 'ในชื่อเรื่อง: ',
    fa: 'در عنوان: ',
    sw: 'Kwenye kichwa: ',
    id: 'Di judul: ',
    nl: 'In titel: ',
  },
  inDescriptionCount: {
    ar: 'في الوصف: ',
    en: 'In description: ',
    zh: '在描述中: ',
    es: 'En la descripción: ',
    hi: 'विवरण में: ',
    fr: 'Dans la description: ',
    bn: 'বর্ণনায়: ',
    pt: 'Na descrição: ',
    ru: 'В описании: ',
    ja: '説明内: ',
    de: 'In der Beschreibung: ',
    ko: '설명: ',
    tr: 'Açıklamada: ',
    vi: 'Trong mô tả: ',
    it: 'Nella descrizione: ',
    th: 'ในคำอธิบาย: ',
    fa: 'در توضیحات: ',
    sw: 'Kwenye maelezo: ',
    id: 'Di deskripsi: ',
    nl: 'In beschrijving: ',
  },
  densityLabel: {
    ar: 'الكثافة: ',
    en: 'Density: ',
    zh: '密度: ',
    es: 'Densidad: ',
    hi: 'घनत्व: ',
    fr: 'Densité: ',
    bn: 'ঘনত্ব: ',
    pt: 'Densidade: ',
    ru: 'Плотность: ',
    ja: '密度: ',
    de: 'Dichte: ',
    ko: '밀도: ',
    tr: 'Yoğunluk: ',
    vi: 'Mật độ: ',
    it: 'Densità: ',
    th: 'ความหนาแน่น: ',
    fa: 'تراکم: ',
    sw: 'Uzani: ',
    id: 'Kepadatan: ',
    nl: 'Dichtheid: ',
  },
  keywords: {
    ar: 'الكلمات المفتاحية',
    en: 'Keywords',
    zh: '关键词',
    es: 'Palabras clave',
    hi: 'कीवर्ड',
    fr: 'Mots-clés',
    bn: 'কীওয়ার্ড',
    pt: 'Palavras-chave',
    ru: 'Ключевые слова',
    ja: 'キーワード',
    de: 'Keywords',
    ko: '키워드',
    tr: 'Anahtar Kelimeler',
    vi: 'Từ khóa',
    it: 'Parole chiave',
    th: 'คีย์เวิร์ด',
    fa: 'کلمات کلیدی',
    sw: 'Maneno muhimu',
    id: 'Kata Kunci',
    nl: 'Trefwoorden',
  },
  noKeywords: {
    ar: 'لم يتم إضافة أي كلمة مفتاحية',
    en: 'No keywords added',
    zh: '未添加任何关键词',
    es: 'No se agregaron palabras clave',
    hi: 'कोई कीवर्ड नहीं जोड़ा गया',
    fr: 'Aucun mot-clé ajouté',
    bn: 'কোন কীওয়ার্ড যোগ করা হয়নি',
    pt: 'Nenhuma palavra-chave adicionada',
    ru: 'Ключевые слова не добавлены',
    ja: 'キーワードが追加されていません',
    de: 'Keine Keywords hinzugefügt',
    ko: '키워드가 추가되지 않음',
    tr: 'Hiçbir anahtar kelime eklenmedi',
    vi: 'Chưa thêm từ khóa nào',
    it: 'Nessuna parola chiave aggiunta',
    th: 'ยังไม่ได้เพิ่มคีย์เวิร์ด',
    fa: 'هیچ کلمه کلیدی اضافه نشده است',
    sw: 'Hakuna maneno muhimu yaliyoongezwa',
    id: 'Belum ada kata kunci ditambahkan',
    nl: 'Geen trefwoorden toegevoegd',
  },
  keywordCount: {
    ar: 'عدد الكلمات',
    en: 'Keyword count',
    zh: '关键词数量',
    es: 'Cantidad de palabras clave',
    hi: 'कीवर्ड संख्या',
    fr: 'Nombre de mots-clés',
    bn: 'কীওয়ার্ড সংখ্যা',
    pt: 'Quantidade de palavras-chave',
    ru: 'Количество ключевых слов',
    ja: 'キーワード数',
    de: 'Keyword-Anzahl',
    ko: '키워드 수',
    tr: 'Anahtar kelime sayısı',
    vi: 'Số lượng từ khóa',
    it: 'Numero di parole chiave',
    th: 'จำนวนคีย์เวิร์ด',
    fa: 'تعداد کلمات کلیدی',
    sw: 'Idadi ya maneno muhimu',
    id: 'Jumlah kata kunci',
    nl: 'Aantal trefwoorden',
  },
  keywordCountIdeal: {
    ar: '2-8 مثالي',
    en: '2-8 ideal',
    zh: '2-8 理想',
    es: '2-8 ideal',
    hi: '2-8 आदर्श',
    fr: '2-8 idéal',
    bn: '2-8 আদর্শ',
    pt: '2-8 ideal',
    ru: '2-8 идеально',
    ja: '2-8 理想的',
    de: '2-8 ideal',
    ko: '2-8 적정',
    tr: '2-8 ideal',
    vi: '2-8 lý tưởng',
    it: '2-8 ideale',
    th: '2-8 เหมาะสม',
    fa: '2-8 ایده‌آل',
    sw: '2-8 bora',
    id: '2-8 ideal',
    nl: '2-8 ideaal',
  },
  keywordCountMax: {
    ar: '10 كحد أقصى',
    en: '10 max',
    zh: '最多10个',
    es: '10 máx.',
    hi: 'अधिकतम 10',
    fr: '10 max.',
    bn: 'সর্বোচ্চ ১০',
    pt: '10 máx.',
    ru: 'Макс. 10',
    ja: '最大10',
    de: 'Max. 10',
    ko: '최대 10',
    tr: 'En fazla 10',
    vi: 'Tối đa 10',
    it: 'Max 10',
    th: 'สูงสุด 10',
    fa: 'حداکثر ۱۰',
    sw: 'Upeo 10',
    id: 'Maks. 10',
    nl: 'Max. 10',
  },
  tooMany: {
    ar: 'كثير جداً',
    en: 'Too many',
    zh: '太多',
    es: 'Demasiadas',
    hi: 'बहुत अधिक',
    fr: 'Trop nombreux',
    bn: 'অনেক বেশি',
    pt: 'Muitas',
    ru: 'Слишком много',
    ja: '多すぎる',
    de: 'Zu viele',
    ko: '너무 많음',
    tr: 'Çok fazla',
    vi: 'Quá nhiều',
    it: 'Troppe',
    th: 'มากเกินไป',
    fa: 'بیش از حد',
    sw: 'Mengi sana',
    id: 'Terlalu banyak',
    nl: 'Te veel',
  },
  notInTitle: {
    ar: 'لم تظهر أي كلمة في العنوان',
    en: 'No keywords found in title',
    zh: '标题中未找到关键词',
    es: 'No se encontraron palabras clave en el título',
    hi: 'शीर्षक में कोई कीवर्ड नहीं मिला',
    fr: 'Aucun mot-clé trouvé dans le titre',
    bn: 'শিরোনামে কোন কীওয়ার্ড পাওয়া যায়নি',
    pt: 'Nenhuma palavra-chave encontrada no título',
    ru: 'Ключевые слова не найдены в заголовке',
    ja: 'タイトルにキーワードが見つかりません',
    de: 'Keine Keywords im Titel gefunden',
    ko: '제목에서 키워드를 찾을 수 없음',
    tr: 'Başlıkta anahtar kelime bulunamadı',
    vi: 'Không tìm thấy từ khóa trong tiêu đề',
    it: 'Nessuna parola chiave trovata nel titolo',
    th: 'ไม่พบคีย์เวิร์ดในชื่อเรื่อง',
    fa: 'کلمه کلیدی در عنوان یافت نشد',
    sw: 'Hakuna maneno muhimu yaliyopatikana kwenye kichwa',
    id: 'Tidak ada kata kunci ditemukan di judul',
    nl: 'Geen trefwoorden gevonden in titel',
  },
  notInDescription: {
    ar: 'لم تظهر أي كلمة في الوصف',
    en: 'No keywords found in description',
    zh: '描述中未找到关键词',
    es: 'No se encontraron palabras clave en la descripción',
    hi: 'विवरण में कोई कीवर्ड नहीं मिला',
    fr: 'Aucun mot-clé trouvé dans la description',
    bn: 'বর্ণনায় কোন কীওয়ার্ড পাওয়া যায়নি',
    pt: 'Nenhuma palavra-chave encontrada na descrição',
    ru: 'Ключевые слова не найдены в описании',
    ja: '説明にキーワードが見つかりません',
    de: 'Keine Keywords in der Beschreibung gefunden',
    ko: '설명에서 키워드를 찾을 수 없음',
    tr: 'Açıklamada anahtar kelime bulunamadı',
    vi: 'Không tìm thấy từ khóa trong mô tả',
    it: 'Nessuna parola chiave trovata nella descrizione',
    th: 'ไม่พบคีย์เวิร์ดในคำอธิบาย',
    fa: 'کلمه کلیدی در توضیحات یافت نشد',
    sw: 'Hakuna maneno muhimu yaliyopatikana kwenye maelezo',
    id: 'Tidak ada kata kunci ditemukan di deskripsi',
    nl: 'Geen trefwoorden gevonden in beschrijving',
  },
  keywordLength: {
    ar: 'طول الكلمات',
    en: 'Keyword length',
    zh: '关键词长度',
    es: 'Longitud de palabras clave',
    hi: 'कीवर्ड लंबाई',
    fr: 'Longueur des mots-clés',
    bn: 'কীওয়ার্ড দৈর্ঘ্য',
    pt: 'Comprimento das palavras-chave',
    ru: 'Длина ключевых слов',
    ja: 'キーワードの長さ',
    de: 'Keyword-Länge',
    ko: '키워드 길이',
    tr: 'Anahtar kelime uzunluğu',
    vi: 'Độ dài từ khóa',
    it: 'Lunghezza parola chiave',
    th: 'ความยาวคีย์เวิร์ด',
    fa: 'طول کلمات کلیدی',
    sw: 'Urefu wa neno muhimu',
    id: 'Panjang kata kunci',
    nl: 'Trefwoordlengte',
  },
  avg: {
    ar: 'متوسط',
    en: 'Avg',
    zh: '平均',
    es: 'Prom.',
    hi: 'औसत',
    fr: 'Moy.',
    bn: 'গড়',
    pt: 'Méd.',
    ru: 'Ср.',
    ja: '平均',
    de: 'Ø',
    ko: '평균',
    tr: 'Ort.',
    vi: 'TB',
    it: 'Media',
    th: 'เฉลี่ย',
    fa: 'میانگین',
    sw: 'Wastani',
    id: 'Rata-rata',
    nl: 'Gem.',
  },
  char: {
    ar: 'حرف',
    en: 'chars',
    zh: '字符',
    es: 'carac.',
    hi: 'अक्षर',
    fr: 'car.',
    bn: 'অক্ষর',
    pt: 'carac.',
    ru: 'симв.',
    ja: '文字',
    de: 'Zeichen',
    ko: '글자',
    tr: 'kar.',
    vi: 'ký tự',
    it: 'car.',
    th: 'ตัวอักษร',
    fa: 'حرف',
    sw: 'herufi',
    id: 'kar.',
    nl: 'tekens',
  },
  keywordDensity: {
    ar: 'كثافة الكلمات',
    en: 'Keyword density',
    zh: '关键词密度',
    es: 'Densidad de palabras clave',
    hi: 'कीवर्ड घनत्व',
    fr: 'Densité des mots-clés',
    bn: 'কীওয়ার্ড ঘনত্ব',
    pt: 'Densidade de palavras-chave',
    ru: 'Плотность ключевых слов',
    ja: 'キーワード密度',
    de: 'Keyword-Dichte',
    ko: '키워드 밀도',
    tr: 'Anahtar kelime yoğunluğu',
    vi: 'Mật độ từ khóa',
    it: 'Densità di parole chiave',
    th: 'ความหนาแน่นของคีย์เวิร์ด',
    fa: 'تراکم کلمات کلیدی',
    sw: 'Uzani wa maneno muhimu',
    id: 'Kepadatan kata kunci',
    nl: 'Trefwoorddichtheid',
  },
  allNatural: {
    ar: 'كل الكلمات ضمن الحد الطبيعي',
    en: 'All keywords within natural limit',
    zh: '所有关键词均在自然范围内',
    es: 'Todas las palabras clave dentro del límite natural',
    hi: 'सभी कीवर्ड प्राकृतिक सीमा के भीतर',
    fr: 'Tous les mots-clés dans la limite naturelle',
    bn: 'সব কীওয়ার্ড স্বাভাবিক সীমার মধ্যে',
    pt: 'Todas as palavras-chave dentro do limite natural',
    ru: 'Все ключевые слова в пределах нормы',
    ja: 'すべてのキーワードが自然な範囲内',
    de: 'Alle Keywords innerhalb der natürlichen Grenze',
    ko: '모든 키워드가 자연스러운 범위 내',
    tr: 'Tüm anahtar kelimeler doğal sınır içinde',
    vi: 'Tất cả từ khóa trong giới hạn tự nhiên',
    it: 'Tutte le parole chiave entro il limite naturale',
    th: 'คีย์เวิร์ดทั้งหมดอยู่ในขีดจำกัดธรรมชาติ',
    fa: 'همه کلمات کلیدی در محدوده طبیعی',
    sw: 'Maneno muhimu yote yapo ndani ya kikomo cha asili',
    id: 'Semua kata kunci dalam batas wajar',
    nl: 'Alle trefwoorden binnen natuurlijke limiet',
  },
  densityExceed: {
    ar: 'كلمة تتجاوز 3% كثافة',
    en: 'keyword(s) exceed 3% density',
    zh: '个关键词超过3%密度',
    es: 'palabra(s) clave superan el 3% de densidad',
    hi: 'कीवर्ड 3% घनत्व से अधिक',
    fr: 'mot(s)-clé(s) dépassent 3% de densité',
    bn: 'টি কীওয়ার্ড ৩% ঘনত্ব অতিক্রম করেছে',
    pt: 'palavra(s)-chave excedem 3% de densidade',
    ru: 'ключевых слов превышают 3% плотности',
    ja: 'のキーワードが密度3%を超えています',
    de: 'Keyword(s) überschreiten 3% Dichte',
    ko: '개 키워드가 3% 밀도 초과',
    tr: 'anahtar kelime %3 yoğunluğu aşıyor',
    vi: 'từ khóa vượt quá 3% mật độ',
    it: 'parola(e) chiave superano il 3% di densità',
    th: 'คีย์เวิร์ดมีความหนาแน่นเกิน 3%',
    fa: 'کلمه کلیدی بیش از ۳٪ تراکم',
    sw: 'neno/maneno muhimu yanazidi 3% uzani',
    id: 'kata kunci melebihi 3% kepadatan',
    nl: 'trefwoord(en) overschrijden 3% dichtheid',
  },
  title: {
    ar: 'العنوان',
    en: 'Title',
    zh: '标题',
    es: 'Título',
    hi: 'शीर्षक',
    fr: 'Titre',
    bn: 'শিরোনাম',
    pt: 'Título',
    ru: 'Заголовок',
    ja: 'タイトル',
    de: 'Titel',
    ko: '제목',
    tr: 'Başlık',
    vi: 'Tiêu đề',
    it: 'Titolo',
    th: 'ชื่อเรื่อง',
    fa: 'عنوان',
    sw: 'Kichwa',
    id: 'Judul',
    nl: 'Titel',
  },
  titleEmpty: {
    ar: 'العنوان فارغ',
    en: 'Title is empty',
    zh: '标题为空',
    es: 'El título está vacío',
    hi: 'शीर्षक खाली है',
    fr: 'Le titre est vide',
    bn: 'শিরোনাম খালি',
    pt: 'O título está vazio',
    ru: 'Заголовок пуст',
    ja: 'タイトルが空です',
    de: 'Titel ist leer',
    ko: '제목이 비어 있음',
    tr: 'Başlık boş',
    vi: 'Tiêu đề trống',
    it: 'Il titolo è vuoto',
    th: 'ชื่อเรื่องว่างเปล่า',
    fa: 'عنوان خالی است',
    sw: 'Kichwa hakina kitu',
    id: 'Judul kosong',
    nl: 'Titel is leeg',
  },
  titleLength: {
    ar: 'طول العنوان',
    en: 'Title length',
    zh: '标题长度',
    es: 'Longitud del título',
    hi: 'शीर्षक लंबाई',
    fr: 'Longueur du titre',
    bn: 'শিরোনামের দৈর্ঘ্য',
    pt: 'Comprimento do título',
    ru: 'Длина заголовка',
    ja: 'タイトルの長さ',
    de: 'Titellänge',
    ko: '제목 길이',
    tr: 'Başlık uzunluğu',
    vi: 'Độ dài tiêu đề',
    it: 'Lunghezza titolo',
    th: 'ความยาวชื่อเรื่อง',
    fa: 'طول عنوان',
    sw: 'Urefu wa kichwa',
    id: 'Panjang judul',
    nl: 'Titellengte',
  },
  charsMax: {
    ar: 'حرفاً',
    en: 'chars max',
    zh: '字符以内',
    es: 'carac. máx.',
    hi: 'अक्षर अधिकतम',
    fr: 'car. max.',
    bn: 'অক্ষর সর্বোচ্চ',
    pt: 'carac. máx.',
    ru: 'симв. макс.',
    ja: '文字以内',
    de: 'Zeichen max.',
    ko: '글자 이내',
    tr: 'kar. maks.',
    vi: 'ký tự tối đa',
    it: 'car. max',
    th: 'ตัวอักษรสูงสุด',
    fa: 'حرف حداکثر',
    sw: 'herufi upeo',
    id: 'kar. maks.',
    nl: 'tekens max.',
  },
  tooShort: {
    ar: 'قصير جداً',
    en: 'too short',
    zh: '太短',
    es: 'demasiado corto',
    hi: 'बहुत छोटा',
    fr: 'trop court',
    bn: 'অতিরিক্ত ছোট',
    pt: 'muito curto',
    ru: 'слишком короткий',
    ja: '短すぎる',
    de: 'zu kurz',
    ko: '너무 짧음',
    tr: 'çok kısa',
    vi: 'quá ngắn',
    it: 'troppo corto',
    th: 'สั้นเกินไป',
    fa: 'خیلی کوتاه',
    sw: 'mfupi sana',
    id: 'terlalu pendek',
    nl: 'te kort',
  },
  description: {
    ar: 'الوصف',
    en: 'Description',
    zh: '描述',
    es: 'Descripción',
    hi: 'विवरण',
    fr: 'Description',
    bn: 'বর্ণনা',
    pt: 'Descrição',
    ru: 'Описание',
    ja: '説明',
    de: 'Beschreibung',
    ko: '설명',
    tr: 'Açıklama',
    vi: 'Mô tả',
    it: 'Descrizione',
    th: 'คำอธิบาย',
    fa: 'توضیحات',
    sw: 'Maelezo',
    id: 'Deskripsi',
    nl: 'Beschrijving',
  },
  descEmpty: {
    ar: 'الوصف فارغ',
    en: 'Description is empty',
    zh: '描述为空',
    es: 'La descripción está vacía',
    hi: 'विवरण खाली है',
    fr: 'La description est vide',
    bn: 'বর্ণনা খালি',
    pt: 'A descrição está vazia',
    ru: 'Описание пусто',
    ja: '説明が空です',
    de: 'Beschreibung ist leer',
    ko: '설명이 비어 있음',
    tr: 'Açıklama boş',
    vi: 'Mô tả trống',
    it: 'La descrizione è vuota',
    th: 'คำอธิบายว่างเปล่า',
    fa: 'توضیحات خالی است',
    sw: 'Maelezo hayana kitu',
    id: 'Deskripsi kosong',
    nl: 'Beschrijving is leeg',
  },
  descLength: {
    ar: 'طول الوصف',
    en: 'Description length',
    zh: '描述长度',
    es: 'Longitud de la descripción',
    hi: 'विवरण लंबाई',
    fr: 'Longueur de la description',
    bn: 'বর্ণনার দৈর্ঘ্য',
    pt: 'Comprimento da descrição',
    ru: 'Длина описания',
    ja: '説明の長さ',
    de: 'Beschreibungslänge',
    ko: '설명 길이',
    tr: 'Açıklama uzunluğu',
    vi: 'Độ dài mô tả',
    it: 'Lunghezza descrizione',
    th: 'ความยาวคำอธิบาย',
    fa: 'طول توضیحات',
    sw: 'Urefu wa maelezo',
    id: 'Panjang deskripsi',
    nl: 'Beschrijvingslengte',
  },
  tooLong: {
    ar: 'طويل جداً',
    en: 'too long',
    zh: '太长',
    es: 'demasiado largo',
    hi: 'बहुत लंबा',
    fr: 'trop long',
    bn: 'অতিরিক্ত দীর্ঘ',
    pt: 'muito longo',
    ru: 'слишком длинный',
    ja: '長すぎる',
    de: 'zu lang',
    ko: '너무 김',
    tr: 'çok uzun',
    vi: 'quá dài',
    it: 'troppo lungo',
    th: 'ยาวเกินไป',
    fa: 'خیلی طولانی',
    sw: 'ndefu sana',
    id: 'terlalu panjang',
    nl: 'te lang',
  },
}

export function kwLabel(key, locale) {
  const labels = KEYWORD_LABELS[key]
  if (!labels) return key
  return labels[locale] || labels.en || key
}
